# Generated by Django 5.2.4 on 2025-07-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_wb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="цена (руб.)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="цена со скидкой (руб.)",
            ),
        ),
    ]
