# Generated by Django 5.2.4 on 2025-07-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_wb", "0002_alter_product_price_alter_product_price_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldAppleProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "product_url",
                    models.URLField(
                        max_length=1024, unique=True, verbose_name="Ссылка на продукт"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "rating",
                    models.FloatField(blank=True, null=True, verbose_name="Рейтинг"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание продукта"),
                ),
                (
                    "usage",
                    models.TextField(
                        blank=True, verbose_name="Инструкция по применению"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Страна-производитель"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт (Gold Apple)",
                "verbose_name_plural": "Продукты (Gold Apple)",
            },
        ),
    ]
